[
{"model":"NEMaterialClass","pk":"0","fields":{"name":"Aggregate","subtype":""}},
{"model":"NEMaterialClass","pk":"1","fields":{"name":"Ceramic","subtype":""}},
{"model":"NEMaterialClass","pk":"2","fields":{"name":"Ceramic","subtype":"Fittings"}},
{"model":"NEMaterialClass","pk":"3","fields":{"name":"Ceramic","subtype":"Sanitary Products"}},
{"model":"NEMaterialClass","pk":"4","fields":{"name":"Ceramic","subtype":"Tiles"}},
{"model":"NEMaterialClass","pk":"5","fields":{"name":"Clay","subtype":""}},
{"model":"NEMaterialClass","pk":"6","fields":{"name":"Clay","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"7","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"8","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"9","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"10","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"11","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"12","fields":{"name":"Carpet","subtype":"Polyethylterephtalate"}},
{"model":"NEMaterialClass","pk":"13","fields":{"name":"Carpet","subtype":"Polypropylene"}},
{"model":"NEMaterialClass","pk":"14","fields":{"name":"Carpet","subtype":"Polyurethane"}},
{"model":"NEMaterialClass","pk":"15","fields":{"name":"Carpet","subtype":"Rubber"}},
{"model":"NEMaterialClass","pk":"16","fields":{"name":"Carpet","subtype":"Saturated Felt Underlay"}},
{"model":"NEMaterialClass","pk":"17","fields":{"name":"Carpet","subtype":"Wool"}},
{"model":"NEMaterialClass","pk":"18","fields":{"name":"Cement","subtype":""}},
{"model":"NEMaterialClass","pk":"19","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"20","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"21","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"22","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"23","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"24","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"25","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"26","fields":{"name":"Glass","subtype":"Primary"}},
{"model":"NEMaterialClass","pk":"27","fields":{"name":"Glass","subtype":"Secondary"}},
{"model":"NEMaterialClass","pk":"28","fields":{"name":"Glass","subtype":"Fiberglass"}},
{"model":"NEMaterialClass","pk":"29","fields":{"name":"Glass","subtype":"Toughened"}},
{"model":"NEMaterialClass","pk":"30","fields":{"name":"Insulation","subtype":""}},
{"model":"NEMaterialClass","pk":"31","fields":{"name":"Insulation","subtype":"Cellular Glass"}},
{"model":"NEMaterialClass","pk":"32","fields":{"name":"Insulation","subtype":"Cellulose"}},
{"model":"NEMaterialClass","pk":"33","fields":{"name":"Insulation","subtype":"Cellulose"}},
{"model":"NEMaterialClass","pk":"34","fields":{"name":"Insulation","subtype":"Cork"}},
{"model":"NEMaterialClass","pk":"35","fields":{"name":"Insulation","subtype":"Fiberglass"}},
{"model":"NEMaterialClass","pk":"36","fields":{"name":"Insulation","subtype":"Flax"}},
{"model":"NEMaterialClass","pk":"37","fields":{"name":"Insulation","subtype":"Mineral Wool"}},
{"model":"NEMaterialClass","pk":"38","fields":{"name":"Insulation","subtype":"Paper Wool"}},
{"model":"NEMaterialClass","pk":"39","fields":{"name":"Insulation","subtype":"Rockwool"}},
{"model":"NEMaterialClass","pk":"40","fields":{"name":"Insulation","subtype":"Woodwool"}},
{"model":"NEMaterialClass","pk":"41","fields":{"name":"Insulation","subtype":"Woodwool"}},
{"model":"NEMaterialClass","pk":"42","fields":{"name":"Insulation","subtype":"Wool"}},
{"model":"NEMaterialClass","pk":"43","fields":{"name":"Iron","subtype":""}},
{"model":"NEMaterialClass","pk":"44","fields":{"name":"Lime","subtype":""}},
{"model":"NEMaterialClass","pk":"45","fields":{"name":"Linoleum","subtype":""}},
{"model":"NEMaterialClass","pk":"46","fields":{"name":"Asbestos","subtype":""}},
{"model":"NEMaterialClass","pk":"47","fields":{"name":"Calcium Silicate","subtype":"Sheet"}},
{"model":"NEMaterialClass","pk":"48","fields":{"name":"Chromium","subtype":""}},
{"model":"NEMaterialClass","pk":"49","fields":{"name":"Cotton","subtype":"Padding"}},
{"model":"NEMaterialClass","pk":"50","fields":{"name":"Cotton","subtype":"Fabric"}},
{"model":"NEMaterialClass","pk":"51","fields":{"name":"Damp Proof Course","subtype":""}},
{"model":"NEMaterialClass","pk":"52","fields":{"name":"Felt","subtype":""}},
{"model":"NEMaterialClass","pk":"53","fields":{"name":"Flax","subtype":""}},
{"model":"NEMaterialClass","pk":"54","fields":{"name":"Fly Ash","subtype":""}},
{"model":"NEMaterialClass","pk":"55","fields":{"name":"Grit","subtype":""}},
{"model":"NEMaterialClass","pk":"56","fields":{"name":"Limestone","subtype":"Ground"}},
{"model":"NEMaterialClass","pk":"57","fields":{"name":"Carpet Grout","subtype":""}},
{"model":"NEMaterialClass","pk":"58","fields":{"name":"Plastic","subtype":"Glass-Reinforced"}},
{"model":"NEMaterialClass","pk":"59","fields":{"name":"Lithium","subtype":""}},
{"model":"NEMaterialClass","pk":"60","fields":{"name":"Mandolite","subtype":""}},
{"model":"NEMaterialClass","pk":"61","fields":{"name":"Mineral Fiber","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"62","fields":{"name":"Manganese","subtype":""}},
{"model":"NEMaterialClass","pk":"63","fields":{"name":"Mercury","subtype":""}},
{"model":"NEMaterialClass","pk":"64","fields":{"name":"Molybdenum","subtype":""}},
{"model":"NEMaterialClass","pk":"65","fields":{"name":"Nickel","subtype":""}},
{"model":"NEMaterialClass","pk":"66","fields":{"name":"Perlite","subtype":"Expanded"}},
{"model":"NEMaterialClass","pk":"67","fields":{"name":"Perlite","subtype":"Natural"}},
{"model":"NEMaterialClass","pk":"68","fields":{"name":"Quartz","subtype":"Powder"}},
{"model":"NEMaterialClass","pk":"69","fields":{"name":"Shingle","subtype":""}},
{"model":"NEMaterialClass","pk":"70","fields":{"name":"Silicon","subtype":""}},
{"model":"NEMaterialClass","pk":"71","fields":{"name":"GGBS","subtype":""}},
{"model":"NEMaterialClass","pk":"72","fields":{"name":"Silver","subtype":""}},
{"model":"NEMaterialClass","pk":"73","fields":{"name":"Straw","subtype":""}},
{"model":"NEMaterialClass","pk":"74","fields":{"name":"Terazzo","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"75","fields":{"name":"Tin","subtype":"Plate"}},
{"model":"NEMaterialClass","pk":"76","fields":{"name":"Tin","subtype":"Plate"}},
{"model":"NEMaterialClass","pk":"77","fields":{"name":"Tin","subtype":""}},
{"model":"NEMaterialClass","pk":"78","fields":{"name":"Vanadium","subtype":""}},
{"model":"NEMaterialClass","pk":"79","fields":{"name":"Vermiculite","subtype":"Expanded"}},
{"model":"NEMaterialClass","pk":"80","fields":{"name":"Vermiculite","subtype":"Natural"}},
{"model":"NEMaterialClass","pk":"81","fields":{"name":"Vicuclad","subtype":""}},
{"model":"NEMaterialClass","pk":"82","fields":{"name":"Water","subtype":""}},
{"model":"NEMaterialClass","pk":"83","fields":{"name":"Wax","subtype":""}},
{"model":"NEMaterialClass","pk":"84","fields":{"name":"Wood Stain","subtype":""}},
{"model":"NEMaterialClass","pk":"85","fields":{"name":"Yttrium","subtype":""}},
{"model":"NEMaterialClass","pk":"86","fields":{"name":"Zirconium","subtype":""}},
{"model":"NEMaterialClass","pk":"87","fields":{"name":"Paper","subtype":"Board"}},
{"model":"NEMaterialClass","pk":"88","fields":{"name":"Paper","subtype":"Fine"}},
{"model":"NEMaterialClass","pk":"89","fields":{"name":"Paper","subtype":"Wall"}},
{"model":"NEMaterialClass","pk":"90","fields":{"name":"Sand","subtype":""}},
{"model":"NEMaterialClass","pk":"91","fields":{"name":"Soil","subtype":""}},
{"model":"NEMaterialClass","pk":"92","fields":{"name":"Stone","subtype":""}},
{"model":"NEMaterialClass","pk":"93","fields":{"name":"Stone","subtype":"Granite"}},
{"model":"NEMaterialClass","pk":"94","fields":{"name":"Stone","subtype":"Limestone"}},
{"model":"NEMaterialClass","pk":"95","fields":{"name":"Stone","subtype":"Marble"}},
{"model":"NEMaterialClass","pk":"96","fields":{"name":"Stone","subtype":"Marble"}},
{"model":"NEMaterialClass","pk":"97","fields":{"name":"Stone","subtype":"Sandstone"}},
{"model":"NEMaterialClass","pk":"98","fields":{"name":"Stone","subtype":"Shale"}},
{"model":"NEMaterialClass","pk":"99","fields":{"name":"Stone","subtype":"Slate"}},
{"model":"NEMaterialClass","pk":"100","fields":{"name":"Stone","subtype":"Slate"}},
{"model":"NEMaterialClass","pk":"101","fields":{"name":"Bricks","subtype":""}},
{"model":"NEMaterialClass","pk":"102","fields":{"name":"Bronze","subtype":""}},
{"model":"NEMaterialClass","pk":"103","fields":{"name":"Plaster","subtype":"Gypsum"}},
{"model":"NEMaterial","pk":"7","fields":{"name":"DN 100","mclass":"7"}},
{"model":"NEMaterial","pk":"8","fields":{"name":"DN 150","mclass":"8"}},
{"model":"NEMaterial","pk":"9","fields":{"name":"DN 200","mclass":"9"}},
{"model":"NEMaterial","pk":"10","fields":{"name":"DN 300","mclass":"10"}},
{"model":"NEMaterial","pk":"11","fields":{"name":"DN 500","mclass":"11"}},
{"model":"NEMaterial","pk":"20","fields":{"name":"16/20MPa","mclass":"20"}},
{"model":"NEMaterial","pk":"21","fields":{"name":"20/25MPa","mclass":"21"}},
{"model":"NEMaterial","pk":"22","fields":{"name":"25/30MPa","mclass":"22"}},
{"model":"NEMaterial","pk":"23","fields":{"name":"28/35MPa","mclass":"23"}},
{"model":"NEMaterial","pk":"24","fields":{"name":"32/40MPa","mclass":"24"}},
{"model":"NEMaterial","pk":"25","fields":{"name":"40/50MPa","mclass":"25"}},
{"model":"NEMaterial","pk":"40","fields":{"name":"Loose","mclass":"40"}},
{"model":"NEMaterial","pk":"41","fields":{"name":"Board","mclass":"41"}},
{"model":"NEMaterial","pk":"42","fields":{"name":"Recycled","mclass":"42"}},
{"model":"NEMaterial","pk":"75","fields":{"name":"Coated","mclass":"75"}},
{"model":"NEMaterial","pk":"76","fields":{"name":"Coated","mclass":"76"}},
{"model":"NEMaterial","pk":"96","fields":{"name":"Tile","mclass":"96"}},
{"model":"NEMaterial","pk":"101","fields":{"name":"Limestone","mclass":"101"}},
{"model":"NESurveyInfo","pk":"0","fields":{"resource":"0","valuetype":"EE","value":"0.083","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"1","fields":{"resource":"1","valuetype":"EE","value":"10.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"EE","value":"20.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"EE","value":"29.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"EE","value":"12.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"EE","value":"3.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"EE","value":"6.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"EE","value":"6.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"EE","value":"6.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"EE","value":"7.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"EE","value":"7.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"EE","value":"7.9","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"EE","value":"106.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"EE","value":"95.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"EE","value":"72.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"EE","value":"103.75","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"EE","value":"31.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"EE","value":"106.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"EE","value":"4.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"EE","value":"0.75","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"EE","value":"0.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EE","value":"0.74","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EE","value":"0.78","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"23","fields":{"resource":"23","valuetype":"EE","value":"0.82","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EE","value":"0.88","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EE","value":"1.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"EE","value":"15.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"EE","value":"11.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"EE","value":"28.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"EE","value":"23.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"30","fields":{"resource":"30","valuetype":"EE","value":"45.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"31","fields":{"resource":"31","valuetype":"EE","value":"27.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"32","fields":{"resource":"32","valuetype":"EE","value":"0.94","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"33","fields":{"resource":"33","valuetype":"EE","value":"3.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"34","fields":{"resource":"34","valuetype":"EE","value":"4.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"35","fields":{"resource":"35","valuetype":"EE","value":"28.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"36","fields":{"resource":"36","valuetype":"EE","value":"39.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"EE","value":"16.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"38","fields":{"resource":"38","valuetype":"EE","value":"20.17","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"EE","value":"16.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"40","fields":{"resource":"40","valuetype":"EE","value":"10.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"41","fields":{"resource":"41","valuetype":"EE","value":"20.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"42","fields":{"resource":"42","valuetype":"EE","value":"20.9","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"EE","value":"25.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"44","fields":{"resource":"44","valuetype":"EE","value":"5.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"45","fields":{"resource":"45","valuetype":"EE","value":"25.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"46","fields":{"resource":"46","valuetype":"EE","value":"7.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"47","fields":{"resource":"47","valuetype":"EE","value":"2.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"48","fields":{"resource":"48","valuetype":"EE","value":"83.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"49","fields":{"resource":"49","valuetype":"EE","value":"27.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"50","fields":{"resource":"50","valuetype":"EE","value":"143.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"51","fields":{"resource":"51","valuetype":"EE","value":"134.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"52","fields":{"resource":"52","valuetype":"EE","value":"36.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"53","fields":{"resource":"53","valuetype":"EE","value":"33.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"54","fields":{"resource":"54","valuetype":"EE","value":"0.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"55","fields":{"resource":"55","valuetype":"EE","value":"0.12","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"56","fields":{"resource":"56","valuetype":"EE","value":"0.62","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"57","fields":{"resource":"57","valuetype":"EE","value":"30.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"58","fields":{"resource":"58","valuetype":"EE","value":"100.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"59","fields":{"resource":"59","valuetype":"EE","value":"853.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"60","fields":{"resource":"60","valuetype":"EE","value":"853.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"61","fields":{"resource":"61","valuetype":"EE","value":"37.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"62","fields":{"resource":"62","valuetype":"EE","value":"52.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"63","fields":{"resource":"63","valuetype":"EE","value":"87.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"64","fields":{"resource":"64","valuetype":"EE","value":"378.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"65","fields":{"resource":"65","valuetype":"EE","value":"164.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"66","fields":{"resource":"66","valuetype":"EE","value":"10.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"67","fields":{"resource":"67","valuetype":"EE","value":"0.66","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"68","fields":{"resource":"68","valuetype":"EE","value":"0.85","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"69","fields":{"resource":"69","valuetype":"EE","value":"11.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"70","fields":{"resource":"70","valuetype":"EE","value":"2355.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"71","fields":{"resource":"71","valuetype":"EE","value":"1.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"72","fields":{"resource":"72","valuetype":"EE","value":"128.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"73","fields":{"resource":"73","valuetype":"EE","value":"0.24","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"74","fields":{"resource":"74","valuetype":"EE","value":"1.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"75","fields":{"resource":"75","valuetype":"EE","value":"19.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"76","fields":{"resource":"76","valuetype":"EE","value":"54.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"77","fields":{"resource":"77","valuetype":"EE","value":"250.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"78","fields":{"resource":"78","valuetype":"EE","value":"3710.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"79","fields":{"resource":"79","valuetype":"EE","value":"7.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"80","fields":{"resource":"80","valuetype":"EE","value":"0.72","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"81","fields":{"resource":"81","valuetype":"EE","value":"70.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"82","fields":{"resource":"82","valuetype":"EE","value":"0.01","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"83","fields":{"resource":"83","valuetype":"EE","value":"52.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"84","fields":{"resource":"84","valuetype":"EE","value":"50.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"85","fields":{"resource":"85","valuetype":"EE","value":"1470.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"86","fields":{"resource":"86","valuetype":"EE","value":"1610.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"87","fields":{"resource":"87","valuetype":"EE","value":"24.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"88","fields":{"resource":"88","valuetype":"EE","value":"28.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"89","fields":{"resource":"89","valuetype":"EE","value":"36.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"90","fields":{"resource":"90","valuetype":"EE","value":"0.081","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"91","fields":{"resource":"91","valuetype":"EE","value":"0.45","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"92","fields":{"resource":"92","valuetype":"EE","value":"1.26","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"93","fields":{"resource":"93","valuetype":"EE","value":"11.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"94","fields":{"resource":"94","valuetype":"EE","value":"1.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"95","fields":{"resource":"95","valuetype":"EE","value":"2.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"96","fields":{"resource":"96","valuetype":"EE","value":"3.33","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"97","fields":{"resource":"97","valuetype":"EE","value":"1.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"98","fields":{"resource":"98","valuetype":"EE","value":"0.03","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"99","fields":{"resource":"99","valuetype":"EE","value":"0.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"100","fields":{"resource":"100","valuetype":"EE","value":"1.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"101","fields":{"resource":"101","valuetype":"EE","value":"0.85","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"102","fields":{"resource":"102","valuetype":"EE","value":"69.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"103","fields":{"resource":"103","valuetype":"EE","value":"1.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"0","fields":{"resource":"0","valuetype":"EC","value":"0.0048","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"1","fields":{"resource":"1","valuetype":"EC","value":"0.66","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"EC","value":"1.07","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"EC","value":"1.51","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"EC","value":"0.74","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"EC","value":"0.23","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"EC","value":"0.45","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"EC","value":"0.44","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"EC","value":"0.44","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"EC","value":"0.48","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"EC","value":"0.48","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"EC","value":"0.52","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"EC","value":"5.56","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"EC","value":"4.98","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"EC","value":"3.76","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"EC","value":"5.545","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"EC","value":"1.65","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"EC","value":"5.53","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"EC","value":"0.73","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"EC","value":"0.1","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"EC","value":"0.093","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EC","value":"0.1","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EC","value":"0.106","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"23","fields":{"resource":"23","valuetype":"EC","value":"0.112","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EC","value":"0.123","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EC","value":"0.141","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"EC","value":"0.86","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"EC","value":"0.55","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"EC","value":"1.54","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"EC","value":"1.27","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"30","fields":{"resource":"30","valuetype":"EC","value":"1.86","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"34","fields":{"resource":"34","valuetype":"EC","value":"0.19","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"35","fields":{"resource":"35","valuetype":"EC","value":"1.35","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"36","fields":{"resource":"36","valuetype":"EC","value":"1.7","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"EC","value":"1.2","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"38","fields":{"resource":"38","valuetype":"EC","value":"0.63","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"EC","value":"1.05","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"41","fields":{"resource":"41","valuetype":"EC","value":"0.98","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"EC","value":"1.91","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"44","fields":{"resource":"44","valuetype":"EC","value":"0.76","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"45","fields":{"resource":"45","valuetype":"EC","value":"1.21","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"47","fields":{"resource":"47","valuetype":"EC","value":"0.13","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"48","fields":{"resource":"48","valuetype":"EC","value":"5.39","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"49","fields":{"resource":"49","valuetype":"EC","value":"1.28","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"50","fields":{"resource":"50","valuetype":"EC","value":"6.78","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"51","fields":{"resource":"51","valuetype":"EC","value":"4.2","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"53","fields":{"resource":"53","valuetype":"EC","value":"1.7","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"54","fields":{"resource":"54","valuetype":"EC","value":"0.008","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"55","fields":{"resource":"55","valuetype":"EC","value":"0.01","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"56","fields":{"resource":"56","valuetype":"EC","value":"0.032","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"58","fields":{"resource":"58","valuetype":"EC","value":"8.1","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"59","fields":{"resource":"59","valuetype":"EC","value":"5.3","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"60","fields":{"resource":"60","valuetype":"EC","value":"5.3","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"61","fields":{"resource":"61","valuetype":"EC","value":"2.7","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"62","fields":{"resource":"62","valuetype":"EC","value":"3.5","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"63","fields":{"resource":"63","valuetype":"EC","value":"4.94","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"64","fields":{"resource":"64","valuetype":"EC","value":"30.3","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"65","fields":{"resource":"65","valuetype":"EC","value":"12.4","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"66","fields":{"resource":"66","valuetype":"EC","value":"0.52","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"67","fields":{"resource":"67","valuetype":"EC","value":"0.03","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"68","fields":{"resource":"68","valuetype":"EC","value":"0.02","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"69","fields":{"resource":"69","valuetype":"EC","value":"0.3","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"71","fields":{"resource":"71","valuetype":"EC","value":"0.083","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"72","fields":{"resource":"72","valuetype":"EC","value":"6.31","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"73","fields":{"resource":"73","valuetype":"EC","value":"0.01","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"74","fields":{"resource":"74","valuetype":"EC","value":"0.12","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"75","fields":{"resource":"75","valuetype":"EC","value":"1.04","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"76","fields":{"resource":"76","valuetype":"EC","value":"2.95","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"77","fields":{"resource":"77","valuetype":"EC","value":"13.5","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"78","fields":{"resource":"78","valuetype":"EC","value":"228.0","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"79","fields":{"resource":"79","valuetype":"EC","value":"0.52","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"80","fields":{"resource":"80","valuetype":"EC","value":"0.03","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"82","fields":{"resource":"82","valuetype":"EC","value":"0.001","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"84","fields":{"resource":"84","valuetype":"EC","value":"5.35","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"85","fields":{"resource":"85","valuetype":"EC","value":"84.0","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"86","fields":{"resource":"86","valuetype":"EC","value":"97.2","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"87","fields":{"resource":"87","valuetype":"EC","value":"1.29","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"88","fields":{"resource":"88","valuetype":"EC","value":"1.49","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"89","fields":{"resource":"89","valuetype":"EC","value":"1.93","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"90","fields":{"resource":"90","valuetype":"EC","value":"0.0048","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"91","fields":{"resource":"91","valuetype":"EC","value":"0.023","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"92","fields":{"resource":"92","valuetype":"EC","value":"0.073","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"93","fields":{"resource":"93","valuetype":"EC","value":"0.64","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"94","fields":{"resource":"94","valuetype":"EC","value":"0.087","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"95","fields":{"resource":"95","valuetype":"EC","value":"0.116","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"96","fields":{"resource":"96","valuetype":"EC","value":"0.192","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"97","fields":{"resource":"97","valuetype":"EC","value":"0.058","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"98","fields":{"resource":"98","valuetype":"EC","value":"0.002","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"99","fields":{"resource":"99","valuetype":"EC","value":"0.006","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"100","fields":{"resource":"100","valuetype":"EC","value":"0.058","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"102","fields":{"resource":"102","valuetype":"EC","value":"3.73","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"103","fields":{"resource":"103","valuetype":"EC","value":"0.12","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"1","fields":{"resource":"1","valuetype":"ECe","value":"0.7","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"ECe","value":"1.14","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"ECe","value":"1.61","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"ECe","value":"0.78","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"ECe","value":"0.24","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"ECe","value":"0.48","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"ECe","value":"0.46","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"ECe","value":"0.46","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"ECe","value":"0.5","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"ECe","value":"0.5","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"ECe","value":"0.55","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"ECe","value":"0.74","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"ECe","value":"0.107","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"ECe","value":"0.1","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"ECe","value":"0.107","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"ECe","value":"0.113","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"23","fields":{"resource":"23","valuetype":"ECe","value":"0.12","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"ECe","value":"0.132","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"ECe","value":"0.151","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"ECe","value":"0.91","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"ECe","value":"0.59","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"ECe","value":"1.35","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"ECe","value":"1.28","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"ECe","value":"1.12","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"ECe","value":"2.03","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"44","fields":{"resource":"44","valuetype":"ECe","value":"0.78","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"77","fields":{"resource":"77","valuetype":"ECe","value":"14.47","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"90","fields":{"resource":"90","valuetype":"ECe","value":"0.0051","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"91","fields":{"resource":"91","valuetype":"ECe","value":"0.024","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"92","fields":{"resource":"92","valuetype":"ECe","value":"0.079","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"93","fields":{"resource":"93","valuetype":"ECe","value":"0.7","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"94","fields":{"resource":"94","valuetype":"ECe","value":"0.09","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"95","fields":{"resource":"95","valuetype":"ECe","value":"0.13","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"96","fields":{"resource":"96","valuetype":"ECe","value":"0.21","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"97","fields":{"resource":"97","valuetype":"ECe","value":"0.06","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"98","fields":{"resource":"98","valuetype":"ECe","value":"0.002","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"99","fields":{"resource":"99","valuetype":"ECe","value":"0.007","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"100","fields":{"resource":"100","valuetype":"ECe","value":"0.063","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"102","fields":{"resource":"102","valuetype":"ECe","value":"4.0","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NESurveyInfo","pk":"103","fields":{"resource":"103","valuetype":"ECe","value":"0.13","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u"}},
{"model":"NEMaterialClass","pk":"0","fields":{"name":"!!!","subtype":""}},
{"model":"NEMaterialClass","pk":"1","fields":{"name":"Bitumen","subtype":""}},
{"model":"NEMaterialClass","pk":"2","fields":{"name":"Plastic","subtype":"ABS"}},
{"model":"NEMaterialClass","pk":"3","fields":{"name":"Plastic","subtype":"Polyethylene"}},
{"model":"NEMaterialClass","pk":"4","fields":{"name":"Plastic","subtype":"HDPE"}},
{"model":"NEMaterialClass","pk":"5","fields":{"name":"Plastic","subtype":"HDPE"}},
{"model":"NEMaterialClass","pk":"6","fields":{"name":"Plastic","subtype":"LDPE"}},
{"model":"NEMaterialClass","pk":"7","fields":{"name":"Plastic","subtype":"LDPE"}},
{"model":"NEMaterialClass","pk":"8","fields":{"name":"Plastic","subtype":"Nylon"}},
{"model":"NEMaterialClass","pk":"9","fields":{"name":"Plastic","subtype":"Polycarbonate"}},
{"model":"NEMaterialClass","pk":"10","fields":{"name":"Plastic","subtype":"Polypropylene"}},
{"model":"NEMaterialClass","pk":"11","fields":{"name":"Plastic","subtype":"Polypropylene"}},
{"model":"NEMaterialClass","pk":"12","fields":{"name":"Plastic","subtype":"Polystyrene"}},
{"model":"NEMaterialClass","pk":"13","fields":{"name":"Plastic","subtype":"Polystyrene"}},
{"model":"NEMaterialClass","pk":"14","fields":{"name":"Plastic","subtype":"Polystyrene"}},
{"model":"NEMaterialClass","pk":"15","fields":{"name":"Plastic","subtype":"Polystyrene"}},
{"model":"NEMaterialClass","pk":"16","fields":{"name":"Plastic","subtype":"Polyurethane"}},
{"model":"NEMaterialClass","pk":"17","fields":{"name":"Plastic","subtype":"Polyurethane"}},
{"model":"NEMaterialClass","pk":"18","fields":{"name":"Plastic","subtype":"PVC"}},
{"model":"NEMaterialClass","pk":"19","fields":{"name":"Plastic","subtype":"PVC"}},
{"model":"NEMaterialClass","pk":"20","fields":{"name":"Plastic","subtype":"PVC"}},
{"model":"NEMaterialClass","pk":"21","fields":{"name":"Plastic","subtype":"PVC"}},
{"model":"NEMaterialClass","pk":"22","fields":{"name":"Plastic","subtype":"UPVC"}},
{"model":"NEMaterialClass","pk":"23","fields":{"name":"Plastic","subtype":"Nylon"}},
{"model":"NEMaterialClass","pk":"24","fields":{"name":"Rubber","subtype":""}},
{"model":"NEMaterialClass","pk":"25","fields":{"name":"Sealant","subtype":"Epoxide"}},
{"model":"NEMaterialClass","pk":"26","fields":{"name":"Sealant","subtype":"Mastic"}},
{"model":"NEMaterialClass","pk":"27","fields":{"name":"Sealant","subtype":"Mastic"}},
{"model":"NEMaterialClass","pk":"28","fields":{"name":"Sealant","subtype":"Melamine"}},
{"model":"NEMaterial","pk":"1","fields":{"name":"51","mclass":"1"}},
{"model":"NEMaterial","pk":"4","fields":{"name":"Resin","mclass":"4"}},
{"model":"NEMaterial","pk":"5","fields":{"name":"Pipe","mclass":"5"}},
{"model":"NEMaterial","pk":"6","fields":{"name":"Resin","mclass":"6"}},
{"model":"NEMaterial","pk":"7","fields":{"name":"Film","mclass":"7"}},
{"model":"NEMaterial","pk":"8","fields":{"name":"6 Polymer","mclass":"8"}},
{"model":"NEMaterial","pk":"10","fields":{"name":"Orientated Film","mclass":"10"}},
{"model":"NEMaterial","pk":"11","fields":{"name":"Injection Molding","mclass":"11"}},
{"model":"NEMaterial","pk":"12","fields":{"name":"Expanded","mclass":"12"}},
{"model":"NEMaterial","pk":"13","fields":{"name":"General-Purpose","mclass":"13"}},
{"model":"NEMaterial","pk":"14","fields":{"name":"High-Impact","mclass":"14"}},
{"model":"NEMaterial","pk":"15","fields":{"name":"Thermoformed","mclass":"15"}},
{"model":"NEMaterial","pk":"16","fields":{"name":"Flexible Foam","mclass":"16"}},
{"model":"NEMaterial","pk":"17","fields":{"name":"Rigid Foam","mclass":"17"}},
{"model":"NEMaterial","pk":"19","fields":{"name":"Pipe","mclass":"19"}},
{"model":"NEMaterial","pk":"20","fields":{"name":"Calendered Sheet","mclass":"20"}},
{"model":"NEMaterial","pk":"21","fields":{"name":"Injection Molding","mclass":"21"}},
{"model":"NEMaterial","pk":"22","fields":{"name":"Film","mclass":"22"}},
{"model":"NEMaterial","pk":"23","fields":{"name":"6","mclass":"23"}},
{"model":"NEMaterial","pk":"25","fields":{"name":"Resin","mclass":"25"}},
{"model":"NEMaterial","pk":"28","fields":{"name":"Resin","mclass":"28"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"EE","value":"95.30","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"EE","value":"83.10","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"EE","value":"76.70","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"EE","value":"84.40","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"EE","value":"78.10","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"EE","value":"89.30","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"EE","value":"120.50","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"EE","value":"112.90","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"EE","value":"99.20","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"EE","value":"115.10","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"EE","value":"88.60","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"EE","value":"86.40","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"EE","value":"87.40","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"EE","value":"109.20","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"EE","value":"102.10","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"EE","value":"101.50","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"EE","value":"77.20","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"EE","value":"67.50","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"EE","value":"68.60","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EE","value":"95.10","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EE","value":"69.40","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"23","fields":{"resource":"23","valuetype":"EE","value":"6 Polymer","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EE","value":"91.00","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EE","value":"137.00","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"EE","value":"62","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"EE","value":"200","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"EE","value":"97.00","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"EC","value":"3.05","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"EC","value":"2.04","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"EC","value":"1.57","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"EC","value":"2.02","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"EC","value":"1.69","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"EC","value":"2.13","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"EC","value":"5.47","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"EC","value":"6.03","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"EC","value":"2.97","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"EC","value":"3.93","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"EC","value":"2.55","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"EC","value":"2.71","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"EC","value":"2.76","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"EC","value":"3.45","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"EC","value":"4.06","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"EC","value":"3.48","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"EC","value":"2.61","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"EC","value":"2.56","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"EC","value":"2.61","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EC","value":"2.69","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EC","value":"2.57","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EC","value":"2.66","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EC","value":"5.7","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"ECe","value":"3.76","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"ECe","value":"2.54","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"ECe","value":"1.93","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"ECe","value":"2.52","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"ECe","value":"2.08","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"ECe","value":"2.6","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"ECe","value":"9.14","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"ECe","value":"7.62","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"ECe","value":"3.43","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"ECe","value":"4.49","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"ECe","value":"3.29","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"ECe","value":"3.43","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"ECe","value":"3.42","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"ECe","value":"4.39","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"ECe","value":"4.84","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"ECe","value":"4.26","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"ECe","value":"3.1","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"19","fields":{"resource":"19","valuetype":"ECe","value":"3.23","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"ECe","value":"3.19","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"ECe","value":"3.3","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"ECe","value":"3.16","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"ECe","value":"2.85","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"2","fields":{"resource":"2","valuetype":"FE","value":"48.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"3","fields":{"resource":"3","valuetype":"FE","value":"54.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"4","fields":{"resource":"4","valuetype":"FE","value":"54.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"5","fields":{"resource":"5","valuetype":"FE","value":"55.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"6","fields":{"resource":"6","valuetype":"FE","value":"51.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"7","fields":{"resource":"7","valuetype":"FE","value":"38.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"8","fields":{"resource":"8","valuetype":"FE","value":"50.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"9","fields":{"resource":"9","valuetype":"FE","value":"36.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"10","fields":{"resource":"10","valuetype":"FE","value":"55.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"11","fields":{"resource":"11","valuetype":"FE","value":"54.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"12","fields":{"resource":"12","valuetype":"FE","value":"46.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"13","fields":{"resource":"13","valuetype":"FE","value":"46.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"14","fields":{"resource":"14","valuetype":"FE","value":"46.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"15","fields":{"resource":"15","valuetype":"FE","value":"49.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"16","fields":{"resource":"16","valuetype":"FE","value":"33.47","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"17","fields":{"resource":"17","valuetype":"FE","value":"37.07","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"18","fields":{"resource":"18","valuetype":"FE","value":"28.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"20","fields":{"resource":"20","valuetype":"FE","value":"24.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"FE","value":"35.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"FE","value":"25.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"FE","value":"40.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"FE","value":"42.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NEMaterialClass","pk":"0","fields":{"name":"!!!","subtype":""}},
{"model":"NEMaterialClass","pk":"1","fields":{"name":"Aluminum","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"2","fields":{"name":"Aluminum","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"3","fields":{"name":"Aluminum","subtype":"0.33"}},
{"model":"NEMaterialClass","pk":"4","fields":{"name":"Aluminum","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"5","fields":{"name":"Aluminum","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"6","fields":{"name":"Aluminum","subtype":"0.33"}},
{"model":"NEMaterialClass","pk":"7","fields":{"name":"Aluminum","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"8","fields":{"name":"Aluminum","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"9","fields":{"name":"Aluminum","subtype":"0.33"}},
{"model":"NEMaterialClass","pk":"10","fields":{"name":"Aluminum","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"11","fields":{"name":"Aluminum","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"12","fields":{"name":"Brass","subtype":""}},
{"model":"NEMaterialClass","pk":"13","fields":{"name":"Brass","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"14","fields":{"name":"Brass","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"15","fields":{"name":"Copper","subtype":"0.37"}},
{"model":"NEMaterialClass","pk":"16","fields":{"name":"Copper","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"17","fields":{"name":"Copper","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"18","fields":{"name":"Lead","subtype":"0.61"}},
{"model":"NEMaterialClass","pk":"19","fields":{"name":"Lead","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"20","fields":{"name":"Lead","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"21","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"22","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"23","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"24","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"25","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"26","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"27","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"28","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"29","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"30","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"31","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"32","fields":{"name":"Steel","subtype":"Galvanized"}},
{"model":"NEMaterialClass","pk":"33","fields":{"name":"Steel","subtype":"Galvanized"}},
{"model":"NEMaterialClass","pk":"34","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"35","fields":{"name":"Steel","subtype":"Engineering"}},
{"model":"NEMaterialClass","pk":"36","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"37","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"38","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"39","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"40","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"41","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"42","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"43","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"44","fields":{"name":"Steel","subtype":"Stainless"}},
{"model":"NEMaterialClass","pk":"45","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"46","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"47","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"48","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"49","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"50","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"51","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"52","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"53","fields":{"name":"Steel","subtype":"Galvanized"}},
{"model":"NEMaterialClass","pk":"54","fields":{"name":"Steel","subtype":"Galvanized"}},
{"model":"NEMaterialClass","pk":"55","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"56","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"57","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"58","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"59","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"60","fields":{"name":"Steel","subtype":""}},
{"model":"NEMaterialClass","pk":"61","fields":{"name":"Titanium","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"62","fields":{"name":"Titanium","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"63","fields":{"name":"Titanium","subtype":"1.0"}},
{"model":"NEMaterialClass","pk":"64","fields":{"name":"Zinc","subtype":"0.30"}},
{"model":"NEMaterialClass","pk":"65","fields":{"name":"Zinc","subtype":"0.0"}},
{"model":"NEMaterialClass","pk":"66","fields":{"name":"Zinc","subtype":"1.0"}},
{"model":"NEProduct","pk":"3","fields":{"name":"Cast Products","mclass":"3"}},
{"model":"NEProduct","pk":"4","fields":{"name":"Cast Products","mclass":"4"}},
{"model":"NEProduct","pk":"5","fields":{"name":"Cast Products","mclass":"5"}},
{"model":"NEProduct","pk":"6","fields":{"name":"Extruded","mclass":"6"}},
{"model":"NEProduct","pk":"7","fields":{"name":"Extruded","mclass":"7"}},
{"model":"NEProduct","pk":"8","fields":{"name":"Extruded","mclass":"8"}},
{"model":"NEProduct","pk":"9","fields":{"name":"Rolled","mclass":"9"}},
{"model":"NEProduct","pk":"10","fields":{"name":"Rolled","mclass":"10"}},
{"model":"NEProduct","pk":"11","fields":{"name":"Rolled","mclass":"11"}},
{"model":"NEProduct","pk":"15","fields":{"name":"Tube","mclass":"15"}},
{"model":"NEProduct","pk":"16","fields":{"name":"Tube","mclass":"16"}},
{"model":"NEProduct","pk":"17","fields":{"name":"Tube","mclass":"17"}},
{"model":"NEProduct","pk":"24","fields":{"name":"Bar","mclass":"24"}},
{"model":"NEProduct","pk":"25","fields":{"name":"Rod","mclass":"25"}},
{"model":"NEProduct","pk":"26","fields":{"name":"Bar","mclass":"26"}},
{"model":"NEProduct","pk":"27","fields":{"name":"Rod","mclass":"27"}},
{"model":"NEProduct","pk":"28","fields":{"name":"Bar","mclass":"28"}},
{"model":"NEProduct","pk":"29","fields":{"name":"Rod","mclass":"29"}},
{"model":"NEProduct","pk":"30","fields":{"name":"Coil","mclass":"30"}},
{"model":"NEProduct","pk":"31","fields":{"name":"Coil","mclass":"31"}},
{"model":"NEProduct","pk":"32","fields":{"name":"Coil","mclass":"32"}},
{"model":"NEProduct","pk":"33","fields":{"name":"Coil","mclass":"33"}},
{"model":"NEProduct","pk":"34","fields":{"name":"Coil","mclass":"34"}},
{"model":"NEProduct","pk":"36","fields":{"name":"Pipe","mclass":"36"}},
{"model":"NEProduct","pk":"37","fields":{"name":"Pipe","mclass":"37"}},
{"model":"NEProduct","pk":"38","fields":{"name":"Plate","mclass":"38"}},
{"model":"NEProduct","pk":"39","fields":{"name":"Plate","mclass":"39"}},
{"model":"NEProduct","pk":"40","fields":{"name":"Section","mclass":"40"}},
{"model":"NEProduct","pk":"41","fields":{"name":"Section","mclass":"41"}},
{"model":"NEProduct","pk":"42","fields":{"name":"Section","mclass":"42"}},
{"model":"NEProduct","pk":"43","fields":{"name":"Wire","mclass":"43"}},
{"model":"NEProduct","pk":"47","fields":{"name":"Bar","mclass":"47"}},
{"model":"NEProduct","pk":"48","fields":{"name":"Rod","mclass":"48"}},
{"model":"NEProduct","pk":"49","fields":{"name":"Bar","mclass":"49"}},
{"model":"NEProduct","pk":"50","fields":{"name":"Rod","mclass":"50"}},
{"model":"NEProduct","pk":"51","fields":{"name":"Coil","mclass":"51"}},
{"model":"NEProduct","pk":"52","fields":{"name":"Coil","mclass":"52"}},
{"model":"NEProduct","pk":"53","fields":{"name":"Coil","mclass":"53"}},
{"model":"NEProduct","pk":"54","fields":{"name":"Coil","mclass":"54"}},
{"model":"NEProduct","pk":"55","fields":{"name":"Pipe","mclass":"55"}},
{"model":"NEProduct","pk":"56","fields":{"name":"Pipe","mclass":"56"}},
{"model":"NEProduct","pk":"57","fields":{"name":"Plate","mclass":"57"}},
{"model":"NEProduct","pk":"58","fields":{"name":"Plate","mclass":"58"}},
{"model":"NEProduct","pk":"59","fields":{"name":"Section","mclass":"59"}},
{"model":"NEProduct","pk":"60","fields":{"name":"Section","mclass":"60"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EE","value":"20.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EE","value":"35.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EE","value":"17.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EE","value":"17.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"EE","value":"29.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"EE","value":"29.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"EE","value":"8.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"EE","value":"9.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"30","fields":{"resource":"30","valuetype":"EE","value":"18.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"31","fields":{"resource":"31","valuetype":"EE","value":"32.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"32","fields":{"resource":"32","valuetype":"EE","value":"22.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"33","fields":{"resource":"33","valuetype":"EE","value":"40.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"34","fields":{"resource":"34","valuetype":"EE","value":"29.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"35","fields":{"resource":"35","valuetype":"EE","value":"13.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"36","fields":{"resource":"36","valuetype":"EE","value":"19.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"EE","value":"34.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"38","fields":{"resource":"38","valuetype":"EE","value":"25.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"EE","value":"45.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"40","fields":{"resource":"40","valuetype":"EE","value":"21.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"41","fields":{"resource":"41","valuetype":"EE","value":"38.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"42","fields":{"resource":"42","valuetype":"EE","value":"10.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"EE","value":"36.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"44","fields":{"resource":"44","valuetype":"EE","value":"56.7","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"45","fields":{"resource":"45","valuetype":"EE","value":"26.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"46","fields":{"resource":"46","valuetype":"EE","value":"25.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"47","fields":{"resource":"47","valuetype":"EE","value":"22.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"48","fields":{"resource":"48","valuetype":"EE","value":"22.3","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"49","fields":{"resource":"49","valuetype":"EE","value":"21.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"50","fields":{"resource":"50","valuetype":"EE","value":"21.6","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"51","fields":{"resource":"51","valuetype":"EE","value":"24.4","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"52","fields":{"resource":"52","valuetype":"EE","value":"23.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"53","fields":{"resource":"53","valuetype":"EE","value":"29.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"54","fields":{"resource":"54","valuetype":"EE","value":"28.5","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"55","fields":{"resource":"55","valuetype":"EE","value":"25.8","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"56","fields":{"resource":"56","valuetype":"EE","value":"24.9","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"57","fields":{"resource":"57","valuetype":"EE","value":"33.2","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"58","fields":{"resource":"58","valuetype":"EE","value":"32.0","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"59","fields":{"resource":"59","valuetype":"EE","value":"28.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"60","fields":{"resource":"60","valuetype":"EE","value":"27.1","unit":"MJ/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"EC","value":"1.37","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"EC","value":"2.71","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"EC","value":"1.31","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"EC","value":"1.31","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"EC","value":"2.59","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"EC","value":"2.59","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"EC","value":"0.42","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"EC","value":"0.44","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"30","fields":{"resource":"30","valuetype":"EC","value":"1.3","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"31","fields":{"resource":"31","valuetype":"EC","value":"2.58","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"32","fields":{"resource":"32","valuetype":"EC","value":"1.45","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"33","fields":{"resource":"33","valuetype":"EC","value":"2.84","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"34","fields":{"resource":"34","valuetype":"EC","value":"2.59","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"35","fields":{"resource":"35","valuetype":"EC","value":"0.68","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"36","fields":{"resource":"36","valuetype":"EC","value":"1.37","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"EC","value":"2.71","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"38","fields":{"resource":"38","valuetype":"EC","value":"1.55","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"EC","value":"3.05","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"40","fields":{"resource":"40","valuetype":"EC","value":"1.42","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"41","fields":{"resource":"41","valuetype":"EC","value":"2.82","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"42","fields":{"resource":"42","valuetype":"EC","value":"0.44","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"EC","value":"2.83","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"44","fields":{"resource":"44","valuetype":"EC","value":"6.15","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"45","fields":{"resource":"45","valuetype":"EC","value":"1.9","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"46","fields":{"resource":"46","valuetype":"EC","value":"1.82","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"47","fields":{"resource":"47","valuetype":"EC","value":"1.82","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"48","fields":{"resource":"48","valuetype":"EC","value":"1.82","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"49","fields":{"resource":"49","valuetype":"EC","value":"1.74","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"50","fields":{"resource":"50","valuetype":"EC","value":"1.74","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"51","fields":{"resource":"51","valuetype":"EC","value":"1.81","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"52","fields":{"resource":"52","valuetype":"EC","value":"1.74","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"53","fields":{"resource":"53","valuetype":"EC","value":"2.0","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"54","fields":{"resource":"54","valuetype":"EC","value":"1.92","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"55","fields":{"resource":"55","valuetype":"EC","value":"1.9","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"56","fields":{"resource":"56","valuetype":"EC","value":"1.83","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"57","fields":{"resource":"57","valuetype":"EC","value":"2.15","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"58","fields":{"resource":"58","valuetype":"EC","value":"2.06","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"59","fields":{"resource":"59","valuetype":"EC","value":"1.97","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"60","fields":{"resource":"60","valuetype":"EC","value":"1.89","unit":"kgCO_2/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"21","fields":{"resource":"21","valuetype":"ECe","value":"1.46","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"22","fields":{"resource":"22","valuetype":"ECe","value":"2.89","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"24","fields":{"resource":"24","valuetype":"ECe","value":"1.40","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"25","fields":{"resource":"25","valuetype":"ECe","value":"1.40","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"26","fields":{"resource":"26","valuetype":"ECe","value":"2.77","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"27","fields":{"resource":"27","valuetype":"ECe","value":"2.77","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"28","fields":{"resource":"28","valuetype":"ECe","value":"0.45","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"29","fields":{"resource":"29","valuetype":"ECe","value":"0.47","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"30","fields":{"resource":"30","valuetype":"ECe","value":"1.38","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"31","fields":{"resource":"31","valuetype":"ECe","value":"2.74","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"32","fields":{"resource":"32","valuetype":"ECe","value":"1.54","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"33","fields":{"resource":"33","valuetype":"ECe","value":"3.01","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"34","fields":{"resource":"34","valuetype":"ECe","value":"2.77","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"35","fields":{"resource":"35","valuetype":"ECe","value":"0.72","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"36","fields":{"resource":"36","valuetype":"ECe","value":"1.45","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"37","fields":{"resource":"37","valuetype":"ECe","value":"2.87","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"38","fields":{"resource":"38","valuetype":"ECe","value":"1.66","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"39","fields":{"resource":"39","valuetype":"ECe","value":"3.27","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"40","fields":{"resource":"40","valuetype":"ECe","value":"1.53","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"41","fields":{"resource":"41","valuetype":"ECe","value":"3.03","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"42","fields":{"resource":"42","valuetype":"ECe","value":"0.47","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"43","fields":{"resource":"43","valuetype":"ECe","value":"3.02","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"European Union"}},
{"model":"NESurveyInfo","pk":"45","fields":{"resource":"45","valuetype":"ECe","value":"2.03","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"46","fields":{"resource":"46","valuetype":"ECe","value":"1.95","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"47","fields":{"resource":"47","valuetype":"ECe","value":"1.95","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"48","fields":{"resource":"48","valuetype":"ECe","value":"1.95","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"49","fields":{"resource":"49","valuetype":"ECe","value":"1.86","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"50","fields":{"resource":"50","valuetype":"ECe","value":"1.86","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"51","fields":{"resource":"51","valuetype":"ECe","value":"1.92","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"52","fields":{"resource":"52","valuetype":"ECe","value":"1.85","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"53","fields":{"resource":"53","valuetype":"ECe","value":"2.12","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"54","fields":{"resource":"54","valuetype":"ECe","value":"2.03","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"55","fields":{"resource":"55","valuetype":"ECe","value":"2.01","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"56","fields":{"resource":"56","valuetype":"ECe","value":"1.94","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"57","fields":{"resource":"57","valuetype":"ECe","value":"2.31","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"58","fields":{"resource":"58","valuetype":"ECe","value":"2.21","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
{"model":"NESurveyInfo","pk":"59","fields":{"resource":"59","valuetype":"ECe","value":"2.12","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"Non-EU"}},
{"model":"NESurveyInfo","pk":"60","fields":{"resource":"60","valuetype":"ECe","value":"2.03","unit":"kgCO_2e/kg","startdate":"2011-01-01","infotype":"u","location":"World"}},
]