[
{"model":"NEMaterialClass","pk":"1","fields":{"name":"Aggregate","subtype":""}},
{"model":"NEMaterialClass","pk":"2","fields":{"name":"Ceramic","subtype":""}},
{"model":"NEMaterialClass","pk":"3","fields":{"name":"Ceramic","subtype":"Fittings"}},
{"model":"NEMaterialClass","pk":"4","fields":{"name":"Ceramic","subtype":"Sanitary Products"}},
{"model":"NEMaterialClass","pk":"5","fields":{"name":"Ceramic","subtype":"Tiles"}},
{"model":"NEMaterialClass","pk":"6","fields":{"name":"Clay","subtype":""}},
{"model":"NEMaterialClass","pk":"7","fields":{"name":"Clay","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"8","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"9","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"10","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"11","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"12","fields":{"name":"Clay","subtype":"Vitrified Pipe"}},
{"model":"NEMaterialClass","pk":"13","fields":{"name":"Carpet","subtype":"Polyethylterephtalate"}},
{"model":"NEMaterialClass","pk":"14","fields":{"name":"Carpet","subtype":"Polypropylene"}},
{"model":"NEMaterialClass","pk":"15","fields":{"name":"Carpet","subtype":"Polyurethane"}},
{"model":"NEMaterialClass","pk":"16","fields":{"name":"Carpet","subtype":"Rubber"}},
{"model":"NEMaterialClass","pk":"17","fields":{"name":"Carpet","subtype":"Saturated Felt Underlay"}},
{"model":"NEMaterialClass","pk":"18","fields":{"name":"Carpet","subtype":"Wool"}},
{"model":"NEMaterialClass","pk":"19","fields":{"name":"Cement","subtype":""}},
{"model":"NEMaterialClass","pk":"20","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"21","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"22","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"23","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"24","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"25","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"26","fields":{"name":"Concrete","subtype":""}},
{"model":"NEMaterialClass","pk":"27","fields":{"name":"Glass","subtype":"Primary"}},
{"model":"NEMaterialClass","pk":"28","fields":{"name":"Glass","subtype":"Secondary"}},
{"model":"NEMaterialClass","pk":"29","fields":{"name":"Glass","subtype":"Fiberglass"}},
{"model":"NEMaterialClass","pk":"30","fields":{"name":"Glass","subtype":"Toughened"}},
{"model":"NEMaterialClass","pk":"31","fields":{"name":"Insulation","subtype":""}},
{"model":"NEMaterialClass","pk":"32","fields":{"name":"Insulation","subtype":"Cellular Glass"}},
{"model":"NEMaterialClass","pk":"33","fields":{"name":"Insulation","subtype":"Cellulose"}},
{"model":"NEMaterialClass","pk":"34","fields":{"name":"Insulation","subtype":"Cellulose"}},
{"model":"NEMaterialClass","pk":"35","fields":{"name":"Insulation","subtype":"Cork"}},
{"model":"NEMaterialClass","pk":"36","fields":{"name":"Insulation","subtype":"Fiberglass"}},
{"model":"NEMaterialClass","pk":"37","fields":{"name":"Insulation","subtype":"Flax"}},
{"model":"NEMaterialClass","pk":"38","fields":{"name":"Insulation","subtype":"Mineral Wool"}},
{"model":"NEMaterialClass","pk":"39","fields":{"name":"Insulation","subtype":"Paper Wool"}},
{"model":"NEMaterialClass","pk":"40","fields":{"name":"Insulation","subtype":"Rockwool"}},
{"model":"NEMaterialClass","pk":"41","fields":{"name":"Insulation","subtype":"Woodwool"}},
{"model":"NEMaterialClass","pk":"42","fields":{"name":"Insulation","subtype":"Woodwool"}},
{"model":"NEMaterialClass","pk":"43","fields":{"name":"Insulation","subtype":"Wool"}},
{"model":"NEMaterialClass","pk":"44","fields":{"name":"Iron","subtype":""}},
{"model":"NEMaterialClass","pk":"45","fields":{"name":"Lead","subtype":""}},
{"model":"NEMaterialClass","pk":"46","fields":{"name":"Lead","subtype":""}},
{"model":"NEMaterialClass","pk":"47","fields":{"name":"Lead","subtype":""}},
{"model":"NEMaterialClass","pk":"48","fields":{"name":"Lime","subtype":""}},
{"model":"NEMaterialClass","pk":"49","fields":{"name":"Linoleum","subtype":""}},
{"model":"NEMaterialClass","pk":"50","fields":{"name":"Asbestos","subtype":""}},
{"model":"NEMaterialClass","pk":"51","fields":{"name":"Calcium Silicate","subtype":"Sheet"}},
{"model":"NEMaterialClass","pk":"52","fields":{"name":"Chromium","subtype":""}},
{"model":"NEMaterialClass","pk":"53","fields":{"name":"Cotton","subtype":"Padding"}},
{"model":"NEMaterialClass","pk":"54","fields":{"name":"Cotton","subtype":"Fabric"}},
{"model":"NEMaterialClass","pk":"55","fields":{"name":"Damp Proof Course","subtype":""}},
{"model":"NEMaterialClass","pk":"56","fields":{"name":"Felt","subtype":""}},
{"model":"NEMaterialClass","pk":"57","fields":{"name":"Flax","subtype":""}},
{"model":"NEMaterialClass","pk":"58","fields":{"name":"Fly Ash","subtype":""}},
{"model":"NEMaterialClass","pk":"59","fields":{"name":"Grit","subtype":""}},
{"model":"NEMaterialClass","pk":"60","fields":{"name":"Limestone","subtype":"Ground"}},
{"model":"NEMaterialClass","pk":"61","fields":{"name":"Carpet Grout","subtype":""}},
{"model":"NEMaterialClass","pk":"62","fields":{"name":"Plastic","subtype":"Glass-Reinforced"}},
{"model":"NEMaterialClass","pk":"63","fields":{"name":"Lithium","subtype":""}},
{"model":"NEMaterialClass","pk":"64","fields":{"name":"Mandolite","subtype":""}},
{"model":"NEMaterialClass","pk":"65","fields":{"name":"Mineral Fiber","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"66","fields":{"name":"Manganese","subtype":""}},
{"model":"NEMaterialClass","pk":"67","fields":{"name":"Mercury","subtype":""}},
{"model":"NEMaterialClass","pk":"68","fields":{"name":"Molybdenum","subtype":""}},
{"model":"NEMaterialClass","pk":"69","fields":{"name":"Nickel","subtype":""}},
{"model":"NEMaterialClass","pk":"70","fields":{"name":"Perlite","subtype":"Expanded"}},
{"model":"NEMaterialClass","pk":"71","fields":{"name":"Perlite","subtype":"Natural"}},
{"model":"NEMaterialClass","pk":"72","fields":{"name":"Quartz","subtype":"Powder"}},
{"model":"NEMaterialClass","pk":"73","fields":{"name":"Shingle","subtype":""}},
{"model":"NEMaterialClass","pk":"74","fields":{"name":"Silicon","subtype":""}},
{"model":"NEMaterialClass","pk":"75","fields":{"name":"GGBS","subtype":""}},
{"model":"NEMaterialClass","pk":"76","fields":{"name":"Silver","subtype":""}},
{"model":"NEMaterialClass","pk":"77","fields":{"name":"Straw","subtype":""}},
{"model":"NEMaterialClass","pk":"78","fields":{"name":"Terazzo","subtype":"Tile"}},
{"model":"NEMaterialClass","pk":"79","fields":{"name":"Tin","subtype":"Plate"}},
{"model":"NEMaterialClass","pk":"80","fields":{"name":"Tin","subtype":"Plate"}},
{"model":"NEMaterialClass","pk":"81","fields":{"name":"Tin","subtype":""}},
{"model":"NEMaterialClass","pk":"82","fields":{"name":"Vanadium","subtype":""}},
{"model":"NEMaterialClass","pk":"83","fields":{"name":"Vermiculite","subtype":"Expanded"}},
{"model":"NEMaterialClass","pk":"84","fields":{"name":"Vermiculite","subtype":"Natural"}},
{"model":"NEMaterialClass","pk":"85","fields":{"name":"Vicuclad","subtype":""}},
{"model":"NEMaterialClass","pk":"86","fields":{"name":"Water","subtype":""}},
{"model":"NEMaterialClass","pk":"87","fields":{"name":"Wax","subtype":""}},
{"model":"NEMaterialClass","pk":"88","fields":{"name":"Wood Stain","subtype":""}},
{"model":"NEMaterialClass","pk":"89","fields":{"name":"Yttrium","subtype":""}},
{"model":"NEMaterialClass","pk":"90","fields":{"name":"Zirconium","subtype":""}},
{"model":"NEMaterialClass","pk":"91","fields":{"name":"Paper","subtype":"Board"}},
{"model":"NEMaterialClass","pk":"92","fields":{"name":"Paper","subtype":"Fine"}},
{"model":"NEMaterialClass","pk":"93","fields":{"name":"Paper","subtype":"Wall"}},
{"model":"NEMaterialClass","pk":"94","fields":{"name":"Sand","subtype":""}},
{"model":"NEMaterialClass","pk":"95","fields":{"name":"Soil","subtype":""}},
{"model":"NEMaterialClass","pk":"96","fields":{"name":"Stone","subtype":""}},
{"model":"NEMaterialClass","pk":"97","fields":{"name":"Stone","subtype":"Granite"}},
{"model":"NEMaterialClass","pk":"98","fields":{"name":"Stone","subtype":"Limestone"}},
{"model":"NEMaterialClass","pk":"99","fields":{"name":"Stone","subtype":"Marble"}},
{"model":"NEMaterialClass","pk":"100","fields":{"name":"Stone","subtype":"Marble"}},
{"model":"NEMaterialClass","pk":"101","fields":{"name":"Stone","subtype":"Sandstone"}},
{"model":"NEMaterialClass","pk":"102","fields":{"name":"Stone","subtype":"Shale"}},
{"model":"NEMaterialClass","pk":"103","fields":{"name":"Stone","subtype":"Slate"}},
{"model":"NEMaterialClass","pk":"104","fields":{"name":"Stone","subtype":"Slate"}},
{"model":"NEMaterialClass","pk":"105","fields":{"name":"Bricks","subtype":""}},
{"model":"NEMaterialClass","pk":"106","fields":{"name":"Bronze","subtype":""}},
{"model":"NEMaterialClass","pk":"107","fields":{"name":"Plaster","subtype":"Gypsum"}},
{"model":"NEMaterial","pk"8","fields":{"name":"DN 100","mclass":"8"}},
{"model":"NEMaterial","pk"9","fields":{"name":"DN 150","mclass":"9"}},
{"model":"NEMaterial","pk"10","fields":{"name":"DN 200","mclass":"10"}},
{"model":"NEMaterial","pk"11","fields":{"name":"DN 300","mclass":"11"}},
{"model":"NEMaterial","pk"12","fields":{"name":"DN 500","mclass":"12"}},
{"model":"NEMaterial","pk"21","fields":{"name":"16/20MPa","mclass":"21"}},
{"model":"NEMaterial","pk"22","fields":{"name":"20/25MPa","mclass":"22"}},
{"model":"NEMaterial","pk"23","fields":{"name":"25/30MPa","mclass":"23"}},
{"model":"NEMaterial","pk"24","fields":{"name":"28/35MPa","mclass":"24"}},
{"model":"NEMaterial","pk"25","fields":{"name":"32/40MPa","mclass":"25"}},
{"model":"NEMaterial","pk"26","fields":{"name":"40/50MPa","mclass":"26"}},
{"model":"NEMaterial","pk"41","fields":{"name":"Loose","mclass":"41"}},
{"model":"NEMaterial","pk"42","fields":{"name":"Board","mclass":"42"}},
{"model":"NEMaterial","pk"43","fields":{"name":"Recycled","mclass":"43"}},
{"model":"NEMaterial","pk"46","fields":{"name":"Virgin","mclass":"46"}},
{"model":"NEMaterial","pk"47","fields":{"name":"Recycled","mclass":"47"}},
{"model":"NEMaterial","pk"79","fields":{"name":"Coated","mclass":"79"}},
{"model":"NEMaterial","pk"80","fields":{"name":"Coated","mclass":"80"}},
{"model":"NEMaterial","pk"100","fields":{"name":"Tile","mclass":"100"}},
{"model":"NEMaterial","pk"105","fields":{"name":"Limestone","mclass":"105"}},
]